In [19]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

In [2]:
df = pd.read_csv('/Users/shivendragupta/Desktop/Machine Learning/heart.csv')
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [9]:
from sklearn.model_selection import train_test_split

X = df.iloc[:,0:13]
y = df.iloc[:,-1]

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=.2,random_state=42)
X_train

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
132,42,1,1,120,295,0,1,162,0,0.0,2,0,2
202,58,1,0,150,270,0,0,111,1,0.8,2,0,3
196,46,1,2,150,231,0,1,147,0,3.6,1,0,2
75,55,0,1,135,250,0,0,161,0,1.4,1,0,2
176,60,1,0,117,230,1,1,160,1,1.4,2,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
188,50,1,2,140,233,0,1,163,0,0.6,1,1,3
71,51,1,2,94,227,0,1,154,1,0.0,2,1,3
106,69,1,3,160,234,1,0,131,0,0.1,1,1,2
270,46,1,0,120,249,0,0,144,0,0.8,2,0,3
102,63,0,1,140,195,0,1,179,0,0.0,2,2,2

In [16]:
rf = RandomForestClassifier(n_estimators=1000)

In [17]:
rf.fit(X_train,y_train)

RandomForestClassifier(n_estimators=1000)

In [18]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test,rf.predict(X_test))

0.8524590163934426

In [20]:
gbc = GradientBoostingClassifier()
svc = SVC()
lr = LogisticRegression()

In [21]:
gbc.fit(X_train,y_train)
svc.fit(X_train,y_train)
lr.fit(X_train,y_train)

/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [23]:
print(accuracy_score(y_test,gbc.predict(X_test)))
print(accuracy_score(y_test,svc.predict(X_test)))
print(accuracy_score(y_test,lr.predict(X_test)))

0.7704918032786885
0.7049180327868853
0.8852459016393442

In [27]:
rf_tuned = RandomForestClassifier(max_samples=.75,random_state=42)

In [28]:
rf_tuned.fit(X_train,y_train)

RandomForestClassifier(max_samples=0.75, random_state=42)

In [29]:
accuracy_score(y_test,rf_tuned.predict(X_test))

0.9016393442622951

Hyper Parameter Tuning Using GridSearch cv

In [30]:
from sklearn.model_selection import GridSearchCV

In [31]:
n_estimator = [20,60,100,150,200,300,400,600,700,800,1000]
max_depth = [1,2,3,4,5,6,7,8,9,None]
max_samples = [.25,.5,.75,1]
bootstrap = [True,False]
min_sample_split = [1,2,3,4,5,6]

In [32]:
param_grid = {'n_estimators': n_estimator,
               'max_depth': max_depth,
              'max_samples':max_samples,
              'bootstrap':bootstrap,
              'min_samples_split':min_sample_split,
             }
print(param_grid)

{'n_estimators': [20, 60, 100, 150, 200, 300, 400, 600, 700, 800, 1000], 'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 9, None], 'max_samples': [0.25, 0.5, 0.75, 1], 'bootstrap': [True, False], 'min_samples_split': [1, 2, 3, 4, 5, 6]}

In [33]:

from sklearn.model_selection import GridSearchCV

rf_grid = GridSearchCV(estimator = rf, 
                       param_grid = param_grid, 
                       cv = 5, 
                       verbose=2, 
                       n_jobs = -1)

In [34]:
rf_grid.fit(X_train,y_train)

Fitting 5 folds for each of 5280 candidates, totalling 26400 fits
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=20; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=20; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=20; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=20; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=20; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=60; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=60; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=60; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=60; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=60; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=100; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=100; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=100; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=100; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=100; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=150; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=150; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=150; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=150; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=150; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=200; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=200; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=200; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=200; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=200; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=300; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=300; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=300; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=300; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=300; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=400; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=400; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=400; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=400; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=400; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=600; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=600; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=600; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=600; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=600; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=700; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=700; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=700; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=700; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=700; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=800; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=800; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=800; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=800; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=800; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=1000; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=1000; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=1000; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=1000; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=1, n_estimators=1000; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=20; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=20; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=20; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=20; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=20; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=60; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=60; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=60; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=60; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=60; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=150; total time=   0.1s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=150; total time=   0.1s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=150; total time=   0.1s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=150; total time=   0.1s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=150; total time=   0.1s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=200; total time=   0.1s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=200; total time=   0.1s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=200; total time=   0.1s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=200; total time=   0.1s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=200; total time=   0.1s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=300; total time=   0.1s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=300; total time=   0.1s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=300; total time=   0.1s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=300; total time=   0.1s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=300; total time=   0.1s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=400; total time=   0.2s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=400; total time=   0.2s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=400; total time=   0.2s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=400; total time=   0.2s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=400; total time=   0.2s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=600; total time=   0.3s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=600; total time=   0.3s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=600; total time=   0.3s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=600; total time=   0.3s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=600; total time=   0.3s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=700; total time=   0.3s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=700; total time=   0.3s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=700; total time=   0.3s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=700; total time=   0.3s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=700; total time=   0.3s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=800; total time=   0.3s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=800; total time=   0.4s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=800; total time=   0.4s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=800; total time=   0.4s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=800; total time=   0.4s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=20; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=20; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=1000; total time=   0.5s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=20; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=1000; total time=   0.5s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=20; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=1000; total time=   0.4s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=20; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=1000; total time=   0.4s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=2, n_estimators=1000; total time=   0.4s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=60; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=60; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=60; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=60; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=60; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=100; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=100; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=100; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=100; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=100; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=150; total time=   0.1s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=150; total time=   0.1s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=150; total time=   0.1s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=150; total time=   0.1s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=150; total time=   0.1s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=200; total time=   0.1s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=200; total time=   0.1s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=200; total time=   0.1s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=200; total time=   0.1s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=200; total time=   0.1s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=300; total time=   0.1s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=300; total time=   0.1s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=300; total time=   0.1s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=300; total time=   0.1s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=300; total time=   0.1s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=400; total time=   0.1s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=400; total time=   0.1s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=400; total time=   0.1s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=400; total time=   0.1s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=400; total time=   0.1s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=600; total time=   0.2s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=600; total time=   0.2s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=600; total time=   0.3s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=600; total time=   0.2s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=600; total time=   0.2s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=700; total time=   0.3s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=700; total time=   0.3s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=700; total time=   0.3s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=700; total time=   0.3s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=700; total time=   0.3s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=800; total time=   0.3s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=800; total time=   0.3s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=800; total time=   0.3s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=800; total time=   0.4s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=800; total time=   0.4s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=4, n_estimators=20; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=4, n_estimators=20; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=1000; total time=   0.5s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=1000; total time=   0.5s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=4, n_estimators=20; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=4, n_estimators=20; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=1000; total time=   0.4s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=1000; total time=   0.4s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=4, n_estimators=20; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=3, n_estimators=1000; total time=   0.4s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=4, n_estimators=60; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=4, n_estimators=60; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=4, n_estimators=60; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=4, n_estimators=60; total time=   0.0s
[CV] END bootstrap=True, max_depth=1, max_samples=0.25, min_samples_split=4, n_estimators=60; total time=   0.0s

KeyboardInterrupt: